"""ClarifyDeck OCR diagnostic package (Phase 2F / 2F.1 / 2F.1a).

Native OCR dependencies (RapidOCR / ONNX Runtime) are imported lazily inside
``ocr.runtime`` so that neither ``main.py`` nor the plugin loader ever imports a
native extension during plugin boot. The plugin-local wheel bundle under
``runtime/ocr/site-packages`` is activated only by OCR diagnostic processes via
``ocr.bootstrap``.
"""

from .bootstrap import (
    activate_plugin_ocr_runtime,
    bundle_manifest_path,
    runtime_root,
    runtime_site_packages,
)
from .bundle import (
    BUNDLE_COMPAT_PINS,
    BUNDLE_FORMAT_VERSION,
    BUNDLE_REJECTED_VERSIONS,
    BUILD_HOST_SDIST_PACKAGES,
    DEFAULT_DEVICE_GLIBC,
    DEFAULT_MAXIMUM_MANYLINUX,
    DEFAULT_MINIMUM_MANYLINUX,
    REQUIRED_PACKAGES,
    BundleError,
    BundleManifest,
    BundlePackage,
    BundleTarget,
    build_bundle_manifest,
    is_target_compatible_wheel,
    load_bundle_manifest,
    manylinux_ceiling,
    normalize_dist_name,
    parse_python_version,
    resolver_abis,
    resolver_platforms,
    running_target,
    validate_bundle_compat,
    validate_bundle_manifest,
    wheel_matches_target,
    wheel_tag_summary,
    wheel_tags,
)
from .result import OCRFrameResult, OCRLine
from .stabilizer import (
    DEFAULT_CONSENSUS_REQUIRED,
    DEFAULT_HISTORY_SIZE,
    DEFAULT_MIN_LINE_CONFIDENCE,
    DEFAULT_STALE_TIMEOUT_SEC,
    OCRCandidate,
    OCRStabilizer,
    StableTextEvent,
    StabilizerConfigError,
    StabilizerStats,
    build_candidate_text,
    normalize_line,
)
from .runtime import (
    ALLOWED_DET_LIMIT_TYPES,
    DEFAULT_DET_LIMIT_SIDE_LEN,
    DEFAULT_DET_LIMIT_TYPE,
    ModelManifest,
    OCRConfig,
    OCRError,
    OCRRuntime,
    describe_result,
    load_manifest,
    predict_det_geometry,
    probe_report_lines,
    probe_runtime,
    rgba_to_array,
    validate_assets,
    validate_det_limit_side_len,
    validate_det_limit_type,
)
__all__ = [
    "OCRFrameResult",
    "OCRLine",
    "OCRCandidate",
    "OCRStabilizer",
    "StableTextEvent",
    "StabilizerConfigError",
    "StabilizerStats",
    "build_candidate_text",
    "normalize_line",
    "DEFAULT_MIN_LINE_CONFIDENCE",
    "DEFAULT_CONSENSUS_REQUIRED",
    "DEFAULT_HISTORY_SIZE",
    "DEFAULT_STALE_TIMEOUT_SEC",
    "ModelManifest",
    "OCRConfig",
    "OCRError",
    "OCRRuntime",
    "describe_result",
    "load_manifest",
    "predict_det_geometry",
    "validate_det_limit_side_len",
    "validate_det_limit_type",
    "ALLOWED_DET_LIMIT_TYPES",
    "DEFAULT_DET_LIMIT_SIDE_LEN",
    "DEFAULT_DET_LIMIT_TYPE",
    "probe_report_lines",
    "probe_runtime",
    "rgba_to_array",
    "validate_assets",
    "activate_plugin_ocr_runtime",
    "bundle_manifest_path",
    "runtime_root",
    "runtime_site_packages",
    "BundleError",
    "BundleManifest",
    "BundlePackage",
    "BundleTarget",
    "BUNDLE_COMPAT_PINS",
    "BUNDLE_FORMAT_VERSION",
    "BUNDLE_REJECTED_VERSIONS",
    "BUILD_HOST_SDIST_PACKAGES",
    "DEFAULT_DEVICE_GLIBC",
    "DEFAULT_MAXIMUM_MANYLINUX",
    "DEFAULT_MINIMUM_MANYLINUX",
    "REQUIRED_PACKAGES",
    "build_bundle_manifest",
    "is_target_compatible_wheel",
    "load_bundle_manifest",
    "manylinux_ceiling",
    "normalize_dist_name",
    "parse_python_version",
    "resolver_abis",
    "resolver_platforms",
    "running_target",
    "validate_bundle_compat",
    "validate_bundle_manifest",
    "wheel_matches_target",
    "wheel_tag_summary",
    "wheel_tags",
]
